// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 23/7/2025, 16:44:05
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/anton/WebstormProjects/mecanogame/MecanoGame/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/anton/WebstormProjects/mecanogame/MecanoGame/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/anton/WebstormProjects/mecanogame/MecanoGame/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/anton/WebstormProjects/mecanogame/MecanoGame/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/anton/WebstormProjects/mecanogame/MecanoGame/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/anton/WebstormProjects/mecanogame/MecanoGame/frontend/composables/**/*.{js,ts,mjs}","C:/Users/anton/WebstormProjects/mecanogame/MecanoGame/frontend/utils/**/*.{js,ts,mjs}","C:/Users/anton/WebstormProjects/mecanogame/MecanoGame/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/anton/WebstormProjects/mecanogame/MecanoGame/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/anton/WebstormProjects/mecanogame/MecanoGame/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/anton/WebstormProjects/mecanogame/MecanoGame/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;